### ISSUE TITLE
Error: Cannot find module 'strip-bom-buf'

### ISSUE THREAD

**Issue by itayronen** [svenschoenung/gulp-read#1]
Error: Cannot find module 'strip-bom-buf'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Itay\Projects\Web Projects\db-action-mysql\node_modules\gulp-read\index.js:4:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

This commit moved the dependency.
https://github.com/svenschoenung/gulp-read/commit/5d1bda9ed41d2763be0ca63464db8d6f8aaf7b9d

**Comment by svenschoenung** [comment]
Thanks! Just published a fix as version 1.0.1.

**Comment by itayronen** [comment]
Thank you :)
